config/routes.rb
Rails.application.routes.draw do
  root "movies#index"
  get "/about", to: "home#about_us"
  get "/search", to: "movies#search"
  resources :movies, only: [:index, :show] do
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def landing_page
  end

  def about_us
  end

  private
  def normal_method
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  # before_action :set_page, only: [:index, :search]

  def index
    trending = !params[:trending].nil? ? params[:trending] : "popular"
    begin
      res = RestClient.get "https://api.themoviedb.org/3/movie/#{trending}",
                           { params: {
                             api_key: ENV['MOVIE_API_KEY'],
                             page: get_page
                           }}
      data = JSON.parse(res.body, symbolize_names: true)

      @movies = data[:results]
     @page = data[:page]
      @total_page = data[:total_pages]
    rescue => e
      puts e, "-----"
      render "layouts/404" and return
    end
  end

  def show
    begin
      res = RestClient.get("https://api.themoviedb.org/3/movie/#{params[:id]}" , { params: { api_key: ENV['MOVIE_API_KEY'] }})
      @movie = JSON.parse(res.body, symbolize_names: true)
    rescue => e  # catch all exceptions includes: network error, response err, json parse exception
      puts e, "-----"
      render "layouts/404" and return
    end
    # render "show"
  end

  # route to handle search request and return search result
  def search
    if params[:query].nil?
      redirect_to  root_url and return
    end

    begin
      res = RestClient.get("https://api.themoviedb.org/3/search/movie#{params[:id]}" ,
                           { params: {
                             api_key: ENV['MOVIE_API_KEY'],
                             query: params[:query],
                             page: get_page
                           }})
      data = JSON.parse(res.body, symbolize_names: true)
      @movies = data[:results]
      @page = data[:page]
      @total_page = data[:total_pages]
    rescue => e  # catch all exceptions includes: network error, response err, json parse exception
      puts e, "-----"
      render "layouts/404" and return
    end
    # simple_form

  end

  private
  def set_page
    @page = !params[:page].nil? ? params[:page] : 1
  end

  def get_page
    !params[:page].nil? ? params[:page] : 1
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def merge_params(h)
    hash = {}
    # make a copy of params into hash
    params.each do |key, value|
      hash[key] = value
    end
    # replace existing keys from h
    h.each do |k, v|
      hash[k] = v
    end
    hash
  end
end

app/views/home/about_us.html.erb
<div>
  about page
</div>

app/views/home/landing_page.html.erb
<%= javascript_pack_tag 'landing', 'data-turbolinks-track': 'reload' %>

<div>
  landing page
</div>

app/views/layouts/404.html.erb
404

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Judgeme</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all',  'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "layouts/partials/header" %>
    <%= yield %>
  <%= render "layouts/partials/footer" %>

  </body>
</html>

app/views/layouts/partials/_footer.html.erb
<div>footer</div>

app/views/layouts/partials/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
          Trending
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "Upcoming", movies_path(trending: "upcoming"), class: "dropdown-item" %>
          <%= link_to "Now Playing", movies_path(trending: "now_playing"), class: "dropdown-item" %>
          <%= link_to "Popular", movies_path(trending: "popular"), class: "dropdown-item" %>
          <%= link_to "Top Rated", movies_path(trending: "top_rated"), class: "dropdown-item" %>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled">Disabled</a>
      </li>
    </ul>
    <%= form_with url: search_path, class: "form-inline my-2 my-lg-0", method: :get do |form| %>
      <%= form.text_field :query, class: "form-control mr-sm-2", placeholder: "Search" %>
      <%= form.submit "Search", class:  "btn btn-outline-success my-2 my-sm-0" %>
    <% end %>
  </div>
</nav>

app/views/movies/index.html.erb
<div class="d-flex flex-wrap justify-content-around">
<% @movies.each do |movie| %>
  <%= render "movies/partials/card", movie: movie %>
<% end %>
</div>

app/views/movies/partials/_card.html.erb
<div class="card mb-3" style="width: 18rem;">
  <img src="https://www.themoviedb.org/t/p/w220_and_h330_face<%= movie[:poster_path] %>" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">
      <%= link_to movie[:title], movie_path(movie[:id]) %>
    </h5>
    <p class="card-text"><%= movie[:overview] %></p>
  </div>
</div>

app/views/movies/partials/_movies.html.erb
<%= render "movies/partials/pagination", page: @page, total_page: @total_page %>
<div class="d-flex flex-wrap justify-content-around">
  <% movies.each do |movie| %>
    <%= render "movies/partials/card", movie: movie %>
  <% end %>
</div>

app/views/movies/partials/_pagination.html.erb
<nav aria-label="Page navigation example">
  <ul class="pagination">
    <% if page > 2 %>
      <%= link_to "First", merge_params({controller: controller.controller_name, action: controller.action_name, page: 1}), class: "page-link" %>
    <% end %>
    <% (1..total_page).each do |p| %>
      <li class="page-item">
          <% if p < page + 2 && p > page - 2 %>
            <%= link_to p, merge_params({controller: controller.controller_name, action: controller.action_name, page: p}), class: "page-link" %>
          <% end %>
      </li>
    <% end %>
    <% if page < total_page - 2 %>
      <%= link_to "Last", merge_params({controller: controller.controller_name, action: controller.action_name, page: total_page}), class: "page-link" %>
    <% end %>
  </ul>
</nav>

app/views/movies/search.html.erb
<%= render "movies/partials/movies", movies: @movies %>

app/views/movies/show.html.erb
<div class="d-flex">
  <div class="poster">
    <img src="https://www.themoviedb.org/t/p/w300_and_h450_bestv2/<%= @movie[:poster_path] %>" alt="poster"/>
  </div>
  <div class="details">
    <h1>Title: <%= @movie[:title] %></h1>
  </div>
</div>